/* ================== PRODUCT DATA ==================
   Populated at runtime from js/products.js (auto-generated by the
   admin backend). */
let products = (typeof PRODUCTS !== 'undefined') ? PRODUCTS : [];
let siteCategories = (typeof CATEGORIES !== 'undefined') ? CATEGORIES : [];

let cart = [];
let currentFilter = 'all';
let currentImageIndex = 0;
let currentModalProduct = null;

function tagsChipsHtml(p){
  if(!p.tags || !p.tags.length) return '';
  return `<div class="product-tags" style="display:flex;flex-wrap:wrap;gap:0.3rem;margin:-0.2rem 0 0.5rem;">${p.tags.map(t=>`<span style="font-size:0.62rem;letter-spacing:0.08em;text-transform:uppercase;padding:0.15rem 0.5rem;border:1px solid var(--light-gray,#ddd);border-radius:20px;color:var(--gray,#777);">${t}</span>`).join('')}</div>`;
}

function refreshFromCatalog(){
  products = (typeof PRODUCTS !== 'undefined') ? PRODUCTS : [];
  siteCategories = (typeof CATEGORIES !== 'undefined') ? CATEGORIES : [];
  buildFilterTabs();
  renderProducts();
}
document.addEventListener('catalog:ready', refreshFromCatalog);

function buildFilterTabs(){
  const wrap = document.getElementById('filterTabs');
  if(!wrap || !siteCategories.length) return;
  const active = currentFilter;
  wrap.innerHTML = `<button class="filter-tab ${active==='all'?'active':''}" data-filter="all">All Watches</button>` +
    siteCategories.map(c => `<button class="filter-tab ${active===c?'active':''}" data-filter="${c}">${c}</button>`).join('');
}

function applySiteBranding(){
  const cfg = (typeof _siteConfig !== 'undefined') ? _siteConfig : {};
  const st = (typeof _siteSettings !== 'undefined') ? _siteSettings : {};
  if(st.logoImageUrl){
    document.querySelectorAll('.logo, .footer-logo, .loader-logo').forEach(el=>{
      el.innerHTML = `<img src="${st.logoImageUrl}" alt="${cfg.siteName||'Logo'}" style="height:2em;width:auto;vertical-align:middle;display:inline-block;" />`;
    });
  }
  if(st.faviconUrl){
    const dialLogo = document.getElementById('logoImage');
    if(dialLogo) dialLogo.src = st.faviconUrl;
    let link = document.querySelector("link[rel~='icon']");
    if(!link){ link = document.createElement('link'); link.rel='icon'; document.head.appendChild(link); }
    link.href = st.faviconUrl;
  }
  if(cfg.contactEmail){
    document.querySelectorAll('a[href^="mailto:"]').forEach(a=>a.href = 'mailto:'+cfg.contactEmail);
    document.querySelectorAll('.js-contact-email').forEach(el=>el.textContent = cfg.contactEmail);
  }
  if(cfg.whatsappNumber){
    WHATSAPP_NUMBER = cfg.whatsappNumber;
  }
  document.querySelectorAll('.js-social-instagram').forEach(a=>{ if(cfg.instagramUrl) a.href = cfg.instagramUrl; });
  document.querySelectorAll('.js-social-tiktok').forEach(a=>{ if(cfg.tiktokUrl) a.href = cfg.tiktokUrl; });
  document.querySelectorAll('.js-social-facebook').forEach(a=>{ if(cfg.facebookUrl) a.href = cfg.facebookUrl; });
  document.querySelectorAll('.js-social-youtube').forEach(a=>{ if(cfg.youtubeUrl) a.href = cfg.youtubeUrl; });
  document.querySelectorAll('.js-contact-phone').forEach(el=>{ if(cfg.phone) el.textContent = cfg.phone; });
  document.querySelectorAll('.js-contact-phone-hours').forEach(el=>{ if(cfg.phoneHours) el.textContent = cfg.phoneHours; });
  document.querySelectorAll('.js-contact-address').forEach(el=>{ if(cfg.address) el.textContent = cfg.address; });
  document.querySelectorAll('.js-contact-address-block').forEach(el=>{ if(cfg.address) el.innerHTML = cfg.address.split(',').map(s=>s.trim()).join('<br/>'); });
  if(cfg.whatsappNumber){
    const msg = encodeURIComponent(cfg.whatsappMessage || '');
    document.querySelectorAll('.js-whatsapp-link').forEach(a=>{ a.href = `https://wa.me/${cfg.whatsappNumber}?text=${msg}`; });
  }
  applyAboutSection(cfg.about);
}
document.addEventListener('config:ready', applySiteBranding);
document.addEventListener('settings:ready', applySiteBranding);

function applyAboutSection(about){
  if(!about) return;
  const setText = (id, val) => { const el = document.getElementById(id); if(el && val) el.textContent = val; };
  setText('aboutEyebrow', about.eyebrow);
  setText('aboutTitlePrefix', about.titlePrefix);
  setText('aboutTitleHighlight', about.titleHighlight);
  setText('aboutDescription', about.description);
  setText('aboutStampYear', about.stampYear);
  setText('aboutStampTitle', about.stampTitle);
  setText('aboutStampSubtext', about.stampSubtext);
  setText('aboutButtonText', about.buttonText);
  const img = document.getElementById('aboutImage');
  if(img && about.image) img.src = about.image;
  if(Array.isArray(about.features) && about.features.length){
    const rows = document.querySelectorAll('#aboutFeaturesList .feature-row');
    about.features.slice(0, rows.length).forEach((f, i) => {
      const row = rows[i];
      if(!row) return;
      const titleEl = row.querySelector('.about-feature-title');
      const textEl = row.querySelector('.about-feature-text');
      if(titleEl && f.title) titleEl.textContent = f.title;
      if(textEl && f.text) textEl.textContent = f.text;
    });
  }
}

function renderVideos(){
  const wrap = document.getElementById('videoInner');
  if(!wrap) return;
  const videos = (typeof _siteSettings !== 'undefined' && _siteSettings.videos) ? _siteSettings.videos : [];
  if(!videos.length) return;
  const frames = document.getElementById('videoFrames');
  if(!frames) return;
  frames.innerHTML = videos.map(v => `
    <div class="video-frame reveal in">
      <div class="video-decoration"></div>
      <video controls poster="${v.poster||''}" preload="metadata">
        ${(v.sources||[]).map(s=>`<source src="${s}" type="video/mp4">`).join('')}
        Your browser does not support the video tag.
      </video>
    </div>
  `).join('');
}
document.addEventListener('settings:ready', renderVideos);

window.addEventListener('load',()=>{
  setTimeout(()=>document.getElementById('loader').classList.add('hidden'),800);
  buildFilterTabs();
  renderProducts();
  updateCartUI();
  initScrollAnimations();
  initStickyHeader();
  initReplicaHourMarks();
  if(document.getElementById('handHour')) startWatch();
  applySiteBranding();
  renderVideos();
});

function initStickyHeader(){
  const header = document.getElementById('header');
  window.addEventListener('scroll',()=>{
    if(window.scrollY > 50) header.classList.add('scrolled');
    else header.classList.remove('scrolled');
  });
}

function initScrollAnimations(){
  const observer = new IntersectionObserver((entries)=>{
    entries.forEach(entry=>{
      if(entry.isIntersecting){
        entry.target.classList.add('in');
        observer.unobserve(entry.target);
      }
    });
  },{threshold:0.1,rootMargin:'0px 0px -50px 0px'});
  document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
}

function initReplicaHourMarks(){
  const container = document.getElementById('hourMarksReplica');
  if(!container) return;
  container.style.cssText = 'position:absolute;inset:0;pointer-events:none;';
  let html = '';
  for(let i=0;i<12;i++){
    const rot = i*30;
    const isMajor = i%3===0;
    const cls = isMajor ? 'major' : 'minor';
    html += `<div class="hour-mark ${cls}" style="--rotation:${rot}deg; position:absolute; top:50%; left:50%;"></div>`;
  }
  container.innerHTML = html;

  /* Numerals — positioned with trig so they stay upright and scale responsively */
  const numbers = document.getElementById('hourNumbersReplica');
  if(numbers){
    const radius = 40; /* percent of face radius from center */
    let numHtml = '';
    for(let i=1;i<=12;i++){
      const angleDeg = i*30 - 90;
      const angleRad = angleDeg*Math.PI/180;
      const x = 50 + radius*Math.cos(angleRad);
      const y = 50 + radius*Math.sin(angleRad);
      numHtml += `<div class="hour-number" style="left:${x}%; top:${y}%; transform:translate(-50%,-50%);">${i}</div>`;
    }
    numbers.innerHTML = numHtml;
  }
}

function startWatch(){
  function tick(){
    const now = new Date();
    const h = now.getHours() % 12;
    const m = now.getMinutes();
    const s = now.getSeconds();
    
    const hDeg = (h*30) + (m*0.5);
    const mDeg = m*6 + (s*0.1);
    const sDeg = s*6;
    
    document.getElementById('handHour').style.transform = `translate(-50%,-100%) rotate(${hDeg}deg)`;
    document.getElementById('handMinute').style.transform = `translate(-50%,-100%) rotate(${mDeg}deg)`;
    document.getElementById('handSecond').style.transform = `translate(-50%,-100%) rotate(${sDeg}deg)`;
  }
  tick();
  setInterval(tick,1000);
}

function renderProducts(){
  const grid = document.getElementById('productsGrid');
  if(!grid) return;
  let filtered = currentFilter === 'all' ? products : products.filter(p => p.category === currentFilter);
  
  const sortValue = document.getElementById('sortSelect').value;
  if(sortValue === 'low-high') filtered.sort((a,b)=>a.price-b.price);
  else if(sortValue === 'high-low') filtered.sort((a,b)=>b.price-a.price);
  else if(sortValue === 'newest') filtered.sort((a,b)=>(b.badge==='new'?1:0)-(a.badge==='new'?1:0));
  
  if(filtered.length === 0){
    grid.innerHTML = `<div style="grid-column:1/-1;text-align:center;padding:4rem 1rem;color:var(--gray);">
      <svg width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" style="margin:0 auto 1rem;display:block;opacity:0.3;"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
      <h3 style="font-family:var(--serif);color:var(--black);margin-bottom:0.5rem;">No watches found</h3>
      <p>Try adjusting your filter or search criteria</p>
    </div>`;
    return;
  }
  
  grid.innerHTML = filtered.map((p,i) => `
    <div class="product-card" data-id="${p.id}" style="animation-delay:${i*0.05}s">
      <div class="product-image">
        ${p.badge ? `<span class="product-badge ${p.badge}">${p.badge === 'new' ? 'New' : 'Sale'}</span>` : ''}
        <div class="product-actions">
          <button class="product-action" onclick="event.stopPropagation();toggleWishlist(${p.id})" aria-label="Wishlist">
            <svg viewBox="0 0 24 24"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>
          </button>
          <a class="product-action" href="product.html?id=${p.id}" aria-label="View details">
            <svg viewBox="0 0 24 24"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
          </a>
        </div>
        <a href="product.html?id=${p.id}" style="display:block;width:100%;height:100%;position:absolute;inset:0;z-index:1;"></a>
        <img src="${p.images[0]}" alt="${p.name}" loading="lazy" style="cursor:pointer;position:relative;z-index:0;"/>
      </div>
      <a href="product.html?id=${p.id}" class="product-info" style="text-decoration:none;color:inherit;">
        <div class="product-brand">${p.brand} · ${p.category}</div>
        <div class="product-name">${p.name}</div>
        ${tagsChipsHtml(p)}
        <div class="product-rating">
          <span class="stars">${'★'.repeat(Math.floor(p.rating))}${'☆'.repeat(5-Math.floor(p.rating))}</span>
          <span class="count">(${p.reviews})</span>
        </div>
        <div class="product-price">
          <span class="price-current">PKR ${p.price.toLocaleString()}</span>
          ${p.oldPrice ? `<span class="price-old">PKR ${p.oldPrice.toLocaleString()}</span>` : ''}
        </div>
      </a>
      <button class="product-quick-add" onclick="event.stopPropagation();addToCart(${p.id})">+ Add to Cart</button>
    </div>
  `).join('');
}

if(document.getElementById('filterTabs')){
  document.getElementById('filterTabs').addEventListener('click',(e)=>{
    if(e.target.classList.contains('filter-tab')){
      document.querySelectorAll('.filter-tab').forEach(t=>t.classList.remove('active'));
      e.target.classList.add('active');
      currentFilter = e.target.dataset.filter;
      renderProducts();
    }
  });
}

function sortProducts(value){renderProducts();}

function toggleSearch(){
  const overlay = document.getElementById('searchOverlay');
  overlay.classList.toggle('open');
  if(overlay.classList.contains('open')){
    setTimeout(()=>document.getElementById('searchInput').focus(),400);
  } else {
    document.getElementById('searchInput').value = '';
  }
}
function closeSearchOverlay(e){
  if(e.target === e.currentTarget) toggleSearch();
}
function quickSearch(term){
  document.getElementById('searchInput').value = term;
  handleSearch(term);
}
function handleSearch(value){
  const grid = document.getElementById('productsGrid');
  if(!grid) return;
  if(!value.trim()){renderProducts();return;}
  const results = products.filter(p => 
    p.name.toLowerCase().includes(value.toLowerCase()) || 
    p.category.toLowerCase().includes(value.toLowerCase()) ||
    p.brand.toLowerCase().includes(value.toLowerCase())
  );
  if(results.length === 0){
    grid.innerHTML = `<div style="grid-column:1/-1;text-align:center;padding:4rem 1rem;color:var(--gray);">
      <h3 style="font-family:var(--serif);color:var(--black);margin-bottom:0.5rem;">No results for "${value}"</h3>
      <p>Try a different search term</p>
    </div>`;
    return;
  }
  currentFilter = 'all';
  document.querySelectorAll('.filter-tab').forEach(t=>t.classList.toggle('active',t.dataset.filter==='all'));
  grid.innerHTML = results.map((p,i) => `
    <div class="product-card" data-id="${p.id}">
      <div class="product-image">
        ${p.badge ? `<span class="product-badge ${p.badge}">${p.badge === 'new' ? 'New' : 'Sale'}</span>` : ''}
        <a href="product.html?id=${p.id}" style="display:block;width:100%;height:100%;position:absolute;inset:0;z-index:1;"></a>
        <img src="${p.images[0]}" alt="${p.name}" loading="lazy" style="cursor:pointer;position:relative;z-index:0;"/>
      </div>
      <a href="product.html?id=${p.id}" class="product-info" style="text-decoration:none;color:inherit;">
        <div class="product-brand">${p.brand} · ${p.category}</div>
        <div class="product-name">${p.name}</div>
        ${tagsChipsHtml(p)}
        <div class="product-rating">
          <span class="stars">${'★'.repeat(Math.floor(p.rating))}</span>
          <span class="count">(${p.reviews})</span>
        </div>
        <div class="product-price">
          <span class="price-current">PKR ${p.price.toLocaleString()}</span>
          ${p.oldPrice ? `<span class="price-old">PKR ${p.oldPrice.toLocaleString()}</span>` : ''}
        </div>
      </a>
      <button class="product-quick-add" onclick="event.stopPropagation();addToCart(${p.id})">+ Add to Cart</button>
    </div>
  `).join('');
}

function openModal(id){
  const p = products.find(x => x.id === id);
  if(!p) return;
  currentModalProduct = p;
  currentImageIndex = 0;
  
  const modal = document.getElementById('productModal');
  const content = document.getElementById('modalContent');
  document.getElementById('modalImage').src = p.images[0];
  content.style.backgroundImage = `url(${p.bgImage})`;
  
  const thumbContainer = document.getElementById('modalThumbnails');
  thumbContainer.innerHTML = p.images.map((img,i)=>`
    <div class="modal-thumb ${i===0?'active':''}" onclick="changeModalImage(${i}, this)">
      <img src="${img}" alt="View ${i+1}"/>
    </div>
  `).join('');
  
  document.getElementById('modalInfo').innerHTML = `
    <div class="modal-brand">${p.brand} · ${p.category}</div>
    <h2 class="modal-title">${p.name}</h2>
    <div class="modal-rating">
      <span class="modal-stars">${'★'.repeat(Math.floor(p.rating))}${'☆'.repeat(5-Math.floor(p.rating))}</span>
      <span class="modal-rating-text">${p.rating} · ${p.reviews} reviews</span>
    </div>
    <div class="modal-price-row">
      <span class="modal-price">PKR ${p.price.toLocaleString()}</span>
      ${p.oldPrice ? `<span class="modal-price-old">PKR ${p.oldPrice.toLocaleString()}</span><span class="modal-discount">Save PKR ${(p.oldPrice-p.price).toLocaleString()}</span>` : ''}
    </div>
    <p class="modal-description">${p.desc}</p>
    <div class="modal-features">
      <h4>Key Features</h4>
      <div class="feature-list">
        ${p.features.map(f=>`<div class="feature-item">${f}</div>`).join('')}
      </div>
    </div>
    <div class="qty-selector" id="qtySelector">
      <button class="qty-btn" onclick="changeModalQty(-1)">−</button>
      <span class="qty-value" id="modalQty">1</span>
      <button class="qty-btn" onclick="changeModalQty(1)">+</button>
    </div>
    <div class="modal-actions">
      <button class="btn btn-gold" onclick="modalAddToCart(${p.id})">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
        Add to Cart
      </button>
      <button class="btn btn-whatsapp" onclick="whatsappOrder(${p.id})">
        <svg viewBox="0 0 24 24"><path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z"/></svg>
        Checkout via WhatsApp
      </button>
    </div>
    <div class="modal-meta">
      <div class="meta-item">
        <svg viewBox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>
        <div class="meta-text">Rs. 250 Shipping<br/>All Over Pakistan</div>
      </div>
      <div class="meta-item">
        <svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
        <div class="meta-text">5 Year Warranty</div>
      </div>
      <div class="meta-item">
        <svg viewBox="0 0 24 24"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"/></svg>
        <div class="meta-text">30 Day Returns</div>
      </div>
    </div>
  `;
  modal.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function changeModalImage(index, el){
  if(!currentModalProduct) return;
  currentImageIndex = index;
  document.getElementById('modalImage').style.opacity = '0';
  setTimeout(()=>{
    document.getElementById('modalImage').src = currentModalProduct.images[index];
    document.getElementById('modalImage').style.opacity = '1';
  },150);
  document.querySelectorAll('.modal-thumb').forEach(t=>t.classList.remove('active'));
  if(el) el.classList.add('active');
}

function closeModal(){
  const modal = document.getElementById('productModal');
  if(!modal) return;
  modal.classList.remove('open');
  document.body.style.overflow = '';
}
function changeModalQty(delta){
  const el = document.getElementById('modalQty');
  let v = parseInt(el.textContent) + delta;
  if(v < 1) v = 1;
  if(v > 9) v = 9;
  el.textContent = v;
}

function saveCart(){/* localStorage disabled - cart resets on page refresh */}

function addToCart(id, qty = 1){
  const p = products.find(x => x.id === id);
  if(!p) return;
  const existing = cart.find(x => x.id === id);
  if(existing){
    existing.qty += qty;
  } else {
    cart.push({...p, qty:qty});
  }
  saveCart();
  updateCartUI();
  showToast('Added to Cart',p.name);
  bumpCart();
}

function modalAddToCart(id){
  const qty = parseInt(document.getElementById('modalQty').textContent);
  addToCart(id,qty);
}

function removeFromCart(id){
  cart = cart.filter(x => x.id !== id);
  saveCart();
  updateCartUI();
}

function updateQty(id,delta){
  const item = cart.find(x => x.id === id);
  if(!item) return;
  item.qty += delta;
  if(item.qty < 1) item.qty = 1;
  if(item.qty > 9) item.qty = 9;
  saveCart();
  updateCartUI();
}

function updateCartUI(){
  const total = cart.reduce((s,i)=>s+i.qty,0);
  const subtotal = cart.reduce((s,i)=>s+(i.price*i.qty),0);
  document.getElementById('cartCount').textContent = total;
  document.getElementById('cartDrawerCount').textContent = total;
  
  const body = document.getElementById('cartBody');
  const footer = document.getElementById('cartFooter');
  
  if(cart.length === 0){
    body.innerHTML = `<div class="cart-empty">
      <svg viewBox="0 0 24 24"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
      <h3>Your cart is empty</h3>
      <p>Discover our exquisite collection of luxury timepieces</p>
      <button class="btn btn-primary" onclick="toggleCart();document.getElementById('catalog').scrollIntoView({behavior:'smooth'})">Shop Collection</button>
    </div>`;
    footer.innerHTML = '';
    return;
  }
  
  body.innerHTML = cart.map(item => `
    <div class="cart-item">
      <div class="cart-item-img"><img src="${item.images[0]}" alt="${item.name}"/></div>
      <div class="cart-item-info">
        <div class="cart-item-brand">${item.brand}</div>
        <h4>${item.name}</h4>
        <div class="cart-item-bottom">
          <div class="cart-item-qty">
            <button class="cart-qty-btn" onclick="updateQty(${item.id},-1)">−</button>
            <span class="cart-qty-num">${item.qty}</span>
            <button class="cart-qty-btn" onclick="updateQty(${item.id},1)">+</button>
          </div>
          <div class="cart-item-price">PKR ${(item.price*item.qty).toLocaleString()}</div>
        </div>
        <div class="cart-item-remove" onclick="removeFromCart(${item.id})">Remove</div>
      </div>
    </div>
  `).join('');
  
  const shippingLabel = 'Rs. 250';
  
  footer.innerHTML = `
    <div class="cart-summary">
      <div class="summary-row"><span>Subtotal</span><span>PKR ${subtotal.toLocaleString()}</span></div>
      <div class="summary-row"><span>Shipping (All Over Pakistan)</span><span>${shippingLabel}</span></div>
      <div class="summary-row total"><span>Total</span><span>PKR ${subtotal.toLocaleString()} + ${shippingLabel}</span></div>
    </div>
    <div class="cart-actions">
      <button class="btn btn-whatsapp" onclick="whatsappCheckout()">
        <svg viewBox="0 0 24 24" fill="white"><path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z"/></svg>
        Checkout via WhatsApp — PKR ${subtotal.toLocaleString()} + ${shippingLabel}
      </button>
      <button class="btn btn-outline" onclick="toggleCart()">Continue Shopping</button>
    </div>
  `;
}

function toggleCart(){
  document.getElementById('cartDrawer').classList.toggle('open');
  document.getElementById('cartOverlay').classList.toggle('open');
}

function bumpCart(){
  const el = document.getElementById('cartCount');
  el.classList.remove('bump');
  void el.offsetWidth;
  el.classList.add('bump');
}

let WHATSAPP_NUMBER = (typeof _siteConfig !== 'undefined' && _siteConfig.whatsappNumber) ? _siteConfig.whatsappNumber : '1234567890';

function buildWhatsAppMessage(items, subtotal){
  let msg = `*🕰️ AKFASHION Order Request*\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━\n\n`;
  msg += `*Order Items:*\n`;
  items.forEach((it,i)=>{
    msg += `${i+1}. *${it.name}*\n`;
    msg += `   Brand: ${it.brand}\n`;
    msg += `   Qty: ${it.qty} × PKR ${it.price.toLocaleString()} = *PKR ${(it.price*it.qty).toLocaleString()}*\n\n`;
  });
  msg += `━━━━━━━━━━━━━━━━━━━━\n`;
  msg += `*Subtotal:* PKR ${subtotal.toLocaleString()}\n`;
  msg += `*Shipping:* Rs. 250 (All Over Pakistan)\n`;
  msg += `*Total: PKR ${subtotal.toLocaleString()} + Rs. 250 Shipping* 💰\n\n`;
  msg += `Please share my order details and payment information. Thank you!`;
  return msg;
}

function whatsappOrder(id){
  const p = products.find(x => x.id === id);
  if(!p) return;
  const qty = parseInt(document.getElementById('modalQty').textContent);
  const msg = `*🕰️ AKFASHION Order Request*\n━━━━━━━━━━━━━━━━━━━━\n\n*Order Item:*\n• *${p.name}*\n  Brand: ${p.brand}\n  Category: ${p.category}\n  Qty: ${qty} × PKR ${p.price.toLocaleString()} = *PKR ${(p.price*qty).toLocaleString()}*\n\n━━━━━━━━━━━━━━━━━━━━\n*Subtotal: PKR ${(p.price*qty).toLocaleString()}*\n*Shipping: Rs. 250 (All Over Pakistan)*\n*Total: PKR ${(p.price*qty).toLocaleString()} + Rs. 250 Shipping* 💰\n\nPlease share my order details and payment information. Thank you!`;
  const url = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;
  window.open(url,'_blank');
}

function whatsappCheckout(){
  if(cart.length === 0) return;
  const subtotal = cart.reduce((s,i)=>s+(i.price*i.qty),0);
  const msg = buildWhatsAppMessage(cart,subtotal);
  const url = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;
  window.open(url,'_blank');
}

function showToast(title,message){
  const toast = document.getElementById('toast');
  document.getElementById('toastTitle').textContent = title;
  document.getElementById('toastMessage').textContent = message;
  toast.classList.add('show');
  setTimeout(()=>toast.classList.remove('show'),3500);
}

function scrollToTop(e){
  e.preventDefault();
  window.scrollTo({top:0,behavior:'smooth'});
}

function toggleMobileMenu(){
  document.getElementById('mobileMenu').classList.toggle('open');
}

function toggleWishlist(id){
  const p = products.find(x => x.id === id);
  showToast('Added to Wishlist',p.name);
}

function subscribeNewsletter(e){
  e.preventDefault();
  const input = e.target.querySelector('input');
  showToast('Subscribed Successfully',`Welcome to AKFASHION Inner Circle`);
  input.value = '';
}

document.addEventListener('keydown',(e)=>{
  if(e.key === 'Escape'){
    closeModal();
    if(document.getElementById('searchOverlay').classList.contains('open')) toggleSearch();
    if(document.getElementById('cartDrawer').classList.contains('open')) toggleCart();
    if(document.getElementById('mobileMenu').classList.contains('open')) toggleMobileMenu();
  }
});

document.querySelectorAll('a[href^="#"]').forEach(a=>{
  a.addEventListener('click',function(e){
    const href = this.getAttribute('href');
    if(href === '#') return;
    e.preventDefault();
    const target = document.querySelector(href);
    if(target){
      const offset = 80;
      const top = target.getBoundingClientRect().top + window.pageYOffset - offset;
      window.scrollTo({top,behavior:'smooth'});
    }
  });
});
